myboot.name=Spring \uC6B4\uC601\uD658\uACBD

# log level - info
logging.level.com.rookies6.myspringboot4project=info

# MariaDB config
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/boot_db
spring.datasource.username=boot
spring.datasource.password=boot
spring.datasource.driverClassName=org.mariadb.jdbc.Driver